# Generated by Django 4.2.6 on 2023-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/placeholder.jpg', upload_to='img'),
        ),
    ]
